MvcMusicStore/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using System.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using MvcMusicStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using MvcMusicStore.Repositories;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();

        /// <summary>
        ///     GET: /Store
        ///     List all the genres and if you click on the genre
        ///         it will show all the albums of that genre
        /// </summary>
        /// 
        /// <returns>
        ///     List all the genres and if you click on the genre
        ///         it will show all the albums of that genre
        /// </returns>

        public ActionResult Index()
        {
            StoreRepo storeRepo = new StoreRepo();
            GenreList GenresList = new GenreList();

            // Create a list to hold all the genres
            GenresList.GenresList = new List<Genre>();

            // Get the list of all the genres
            bool success = storeRepo.GenresList(GenresList.GenresList);

            if (success)
            {
                return View(GenresList);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        ///     GET: /Store/Browse?genre=Jazz&genreId=1002
        /// </summary>
        /// 
        /// <param name="genre">
        ///     genre parameter to know the name of the genre selected
        /// </param>
        /// 
        /// <param name="genreID">
        ///     genreId parameter is to know the ID of the genre selected
        /// </param>
        /// 
        /// <returns>
        ///     A list of all the albums belonging to the selected genre
        /// </returns>
      
        public ActionResult Browse(String genre, int genreID)
        {
            StoreRepo storeRepo = new StoreRepo();
            Genre Genres = new Genre();

            Genres.Name = genre;

            // Get the list of albums belonging to the selected genre
            bool success = storeRepo.GenreAlbumsList(Genres, genreID);

            if (success)
            {
                return View(Genres);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        ///     GET: /Store/Details/5
        ///     Collects all the information of the album, including
        ///         the ability to add the album to your cart
        /// </summary>
        /// 
        /// <param name="AlbumId">
        ///     AlbumId provides the ID of the album so you can see 
        ///         the album's information and add it to your cart
        /// </param>
        /// 
        /// <returns>
        ///     Display all the information of the album, including 
        ///         the ability to add the album to your cart
        /// </returns>

        public ActionResult Details(int AlbumId)
        {
            StoreRepo storeRepo = new StoreRepo();
            Album album = new Album();

            // Collect all the information about the album
            bool success = storeRepo.AlbumDetails(album, AlbumId);

            if (success)
            {
                return View(album);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        ///     AJAX: /Store/IndexAJAX
        ///     Using AJAX to fetch the list of genres to display on the left side bar
        ///         of every page so someone can click on the genre and see the albums 
        ///         belonging to that genre on any page they are on
        /// </summary>
        /// 
        /// <returns>
        ///     A JSON string showing a list of all the genres
        /// </returns>
        
        public IActionResult IndexAJAX()
        {
            StoreRepo storeRepo = new StoreRepo();
            GenreList GenresList = new GenreList();

            // Create a list to hold all the genres
            GenresList.GenresList = new List<Genre>();

            // Retrieves and sotres the genres in the list
            bool success = storeRepo.GenresList(GenresList.GenresList);

            if (success)
            {
                return Json( GenresList.GenresList  );
            }
            else
            {
                return View();
            }
        }
    }
}

MvcMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>@ViewData["Title"] - MvcMusicStore</title>

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/MvcMusicStore.styles.css" asp-append-version="true" />
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <h1 id="header">
                        <img src="/Images/logo.png"  />
                        <br />

                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            ASP.NET MVC Music Store
                        </a>
                    </h1>

                    <ul id="navlist">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                Home
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">
                                Store
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOnHeaderRow">
                                Log On
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
                                Shopping Cart
                                <span id="CartItemCount"></span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StoreManager" asp-action="Index">
                                Store Manager
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                <div class="row">
                    <div class="col-md-2" id="LeftBarGenres">
                        <ul id="genreList" class="list-unstyled"></ul>
                    </div>

                    <div class="col-md-10"> 
                        @RenderBody()
                    </div>
                </div>
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2024 - MvcMusicStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @await RenderSectionAsync("Scripts", required: false)
    </body>

    <script type="text/javascript"> 
        $(document).ready(function() 
        {
            //alert("Test1");

            $.get("/Store/IndexAJAX", function(data)
            {
                //alert("Test2");
                //alert(JSON.stringify(data));

                // holds a reference to the genre list element so you can manipulate it
                var genreList = $('#genreList');

                genreList.empty(); 

                $.each(data, function(i, item) 
                {
                    //alert("Test3");
                    //alert(item.name)

                    var genreUrl = '@Url.Action("Browse", "Store")' +
                        '?genre=' + encodeURIComponent(item.name) +
                        '&genreId=' + encodeURIComponent(item.genreId);

                    var genreLink = $('<a>').attr('href', genreUrl).text(item.name);

                    var listItem = $('<li>').append(genreLink);
                    genreList.append(listItem);             
                });
            });
        });

        $(function() 
        {
            $(document).ready(function() 
            {
                //alert("Test1");

                $.post("/ShoppingCart/CartTotalItemsCountAJAX", 
                    function(data) 
                {
                    //alert("Test2");
                    //alert(JSON.stringify(data));

                    $.each(data, function(i, item)
                    {
                        //alert("Test3");
                        //alert(item.cartCount);

                        $('#CartItemCount').text(' (' + item.cartCount + ')');
                    });
                });
            });
        });
    </script>
</html>