MvcMusicStore/Controllers/StoreManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Identity.Client;
using MvcMusicStore.Models;
using MvcMusicStore.Repositories;
using System.ComponentModel;

namespace MvcMusicStore.Controllers
{
    public class StoreManagerController : Controller
    {
        /// <summary>
        ///     GET: /StoreManager
        ///     Shows the list of albums in the inventory 
        ///     Can edit, see the details of, and delete albums in the inventory
        ///     Can add new albums to the inventory
        /// </summary>
        /// 
        /// <returns>
        ///     A list of all the albums in the inventory
        ///     Ability to edit, see the details of, and delete albums in the inventory
        ///     Add new albums to the inventory
        /// </returns>

        public IActionResult Index()
        {
            StoreManagerRepo storemanagerrepo = new StoreManagerRepo(); 
            AlbumList albumlist = new AlbumList();

            ViewData["isPost"] = false;

            // Create a list to hold all the albums in the inventory
            albumlist.albumlist = new List<Album>();

            // Get the list of all the albums in the inventory
            bool success = storemanagerrepo.AllAlbumsList(albumlist.albumlist);

            if (success)
            {
                return View(albumlist);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        ///     GET: /StoreManager/AddNewAlbum
        ///     Add a new album to the inventory by providing all the details of the new album
        /// </summary>
        /// 
        /// <returns>
        ///     A form to add a new album to the inventory and provide all of the album's details
        /// </returns>

        public IActionResult AddNewAlbum()
        {
            StoreManagerRepo storemanagerrepo = new StoreManagerRepo();
            Album NewAlbum = new Album();

            ViewData["isPost"] = false;     

            // Provide a dropdown list to hold all of the album genres
            NewAlbum.SelectGenre = new List<SelectListItem>();

            // Get the list of all of the album genres
            bool success2 = storemanagerrepo.GetNewAlbumListGenre(NewAlbum.SelectGenre);


            // Provide a dropdown list of all of the artists
            NewAlbum.SelectArtist = new List<SelectListItem>();

            // Get the list of all of the artists
            bool success3 = storemanagerrepo.GetNewAlbumListArtist(NewAlbum.SelectArtist);

            if (success2 && success3)
            {
                return View(NewAlbum);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        ///     POST: /StoreManager/AddNewAlbum
        ///     After a new album's information is submitted, it adds the new album
        ///         and it's information to the database
        /// </summary>
        /// 
        /// <param name="NewAlbum">
        ///     Holds the new album's information
        /// </param>
        /// 
        /// <returns>
        ///     A page that says the new album has been successfully added to the database
        /// </returns>

        [HttpPost]
        public IActionResult AddNewAlbum(Album NewAlbum)
        {
            StoreManagerRepo storemanagerrepo = new StoreManagerRepo();

            // Set up an object for a dropdown list of all the genre selections
            NewAlbum.SelectGenre = new List<SelectListItem>();

            // Set up an object for a dropdown list for all the artist selections
            NewAlbum.SelectArtist = new List<SelectListItem>();

            ViewData["isPost"] = true;
            ViewData["indicator"] = false;

            // Checks if the list of selected music genre IDs is not null
            if (NewAlbum.SelectGenreId != null)
            {
                // Checks which genres (by ID) in SelectGenre (contains all possible genres) 
                //    are also in SelectGenreId (containing the genre(s) selected)
                // Holds the genre that was chosen
                List<SelectListItem> ChosenGenre = NewAlbum.SelectGenre.Where
                    (p => NewAlbum.SelectGenreId.Contains(int.Parse(p.Value))).ToList();

                foreach (var genre in ChosenGenre)
                {
                    genre.Selected = true;
                }
            }
            
            if (NewAlbum.SelectArtistId != null)
            {
                // Checks which artists (by ID) in SelectArtist (contains all possible artists) 
                //    are also in SelectArtistId (containing the artist(s) selected) 
                // Holds the artist that was chosen
                List<SelectListItem> ChosenArtist = NewAlbum.SelectArtist.Where
                    (p => NewAlbum.SelectArtistId.Contains(int.Parse(p.Value))).ToList();

                foreach (var artist in ChosenArtist)
                {
                    artist.Selected = true;
                }
            }

            // Checks if the genre, artist, album title, album price, 
            //    and album art url are all valid
            bool success1 = storemanagerrepo.GetNewAlbumID(NewAlbum);
            bool success2 = storemanagerrepo.CheckNewAlbumGenreId(NewAlbum);
            bool success3 = storemanagerrepo.CheckNewAlbumArtistId(NewAlbum);
            bool success4 = storemanagerrepo.CheckNewAlbumTitle(NewAlbum.Title);
            bool success5 = storemanagerrepo.CheckNewAlbumPrice(NewAlbum.Price);
            bool success6 = storemanagerrepo.CheckNewAlbumArtURL(NewAlbum.AlbumArtUrl);

            if (success1 && success2 && success3 & success4 && success5 && success6)
            {
                // Makes sure the album is successfully added to the database
                bool success7 = storemanagerrepo.AddNewAlbum(NewAlbum);

                ViewData["indicator"] = true;

                if (success7 == true)
                {
                    return View(NewAlbum);
                }
                else
                {
                    return View();
                }
            }
            else
            {
                // Get the list of genres to be displayed including
                //    the one you selected (if you selected one)
                NewAlbum.SelectGenre = new List<SelectListItem>();
                storemanagerrepo.GetNewAlbumListGenre(NewAlbum.SelectGenre);

                // Get the list of artists to be displayed including
                //    the one you selected (if you selected one)
                NewAlbum.SelectArtist = new List<SelectListItem>();
                storemanagerrepo.GetNewAlbumListArtist(NewAlbum.SelectArtist);

                return View(NewAlbum);
            }
        }

        /// <summary>
        ///     GET: /StoreManager/Edit
        ///     Provides you a form on how to edit an album's information
        /// </summary>
        /// 
        /// <param name="AlbumId">
        ///     Tells which album's information to edit
        /// </param>
        /// 
        /// <param name="GenreId">
        ///     Tells the id of the genre of the album to be edited
        /// </param>
        /// 
        /// <param name="ArtistId">
        ///     Tells the id of the artist of the album to be edited
        /// </param>
        /// 
        /// <returns>
        ///     Provides a form to edit an album's information
        /// </returns>

        public IActionResult Edit(int AlbumId, int GenreId, int ArtistId) 
        {
            StoreManagerRepo storemanagerrepo = new StoreManagerRepo();
            Album album = new Album();

            ViewData["isPost"] = false;

            album.AlbumId = AlbumId;

            // Retrieve the information of the album whose information you want to edit
            bool success1 = storemanagerrepo.RetrieveAlbumInfo(album, AlbumId);

            // Get the list of all of the album genres
            album.SelectGenre = new List<SelectListItem>();
            bool success2 = storemanagerrepo.ListGenres(album.SelectGenre, GenreId);

            // Get the list of all of the album artists
            album.SelectArtist = new List<SelectListItem>();
            bool success3 = storemanagerrepo.ListArtists(album.SelectArtist, ArtistId);

            if (success1 && success2 && success3)
            {
                return View(album);
            }
            else
            {
                return View();
            }
        }

        /// <summary>
        ///     POST: /StoreManager/Edit
        ///     After an album's information is edited, it updates the album's information
        ///         in the database
        /// </summary>
        /// 
        /// <param name="EditedAlbum">
        ///     Provides the updated information of the album
        /// </param>
        /// 
        /// <returns>
        ///     Tells you that the album's information was successfully updated
        /// </returns>

        [HttpPost]
        public IActionResult Edit(Album EditedAlbum)
        {
            StoreManagerRepo storemanagerrepo = new StoreManagerRepo();

            // Set up an object for a dropdown list of all the genre selections
            EditedAlbum.SelectGenre = new List<SelectListItem>();

            // Set up an object for a dropdown list for all the artist selections
            EditedAlbum.SelectArtist = new List<SelectListItem>();

            ViewData["isPost"] = true;
            ViewData["indicator"] = false;

            // Checks if the list of selected music genre IDs is not null
            if (EditedAlbum.SelectGenreId != null)
            {
                // Checks which genres(by ID) in SelectGenre(contains all possible genres)
                //    are also in SelectGenreId (containing the genre(s) selected)

MvcMusicStore/Views/StoreManager/AddNewAlbum.cshtml
@model MvcMusicStore.Models.Album

@{
    ViewData["Title"] = "Add New Album";
    bool isPost = Convert.ToBoolean(ViewData["isPost"]);
    bool indicator = Convert.ToBoolean(ViewData["indicator"]);
}

<h1>Add New Album</h1>
<br />

@if (isPost == false) 
{
    <div>
        @using (Html.BeginForm("AddNewAlbum", "StoreManager", FormMethod.Post))
        {
            <table>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.SelectGenreId)</td>
                    <td>@Html.DropDownListFor(model => model.SelectGenreId, Model.SelectGenre, "Select Genre")</td>
                </tr>

                <tr>
                    <td>@Html.DisplayNameFor(model => model.SelectArtistId)</td>
                    <td>@Html.DropDownListFor(model => model.SelectArtistId, Model.SelectArtist, "Select Artist")</td>
                </tr>

                <tr>
                    <td>@Html.DisplayNameFor(model => model.Title)</td>
                    <td>
                        <input type="text" name="Title" />
                    </td>
                </tr>

                <tr>
                    <td>@Html.DisplayNameFor(model => model.Price)</td>
                    <td>
                        <input type="text" name="Price" />
                    </td>
                </tr>

                <tr>
                    <td>@Html.DisplayNameFor(model => model.AlbumArtUrl)</td>
                    <td>
                        <input type="text" name="AlbumArtUrl" />
                    </td>
                </tr>

                <tr>
                    <td>
                        <input type="submit" value="Add New Album">
                    </td>
                    <td>
                        <a href="@Url.Action("Index", "StoreManager")">
                            Cancel
                        </a>  
                    </td>
                </tr>
            </table>
        }
    </div>
}
else 
{
    @if (indicator)
    {
        <p>Added the Following album: </p>
        <p>Title: @Model.Title</p>

        <a href="@Url.Action("Index", "StoreManager")"> 
                Click on the link to go back to the list of albums
        </a>
    }
    else
    {
        <div>
            @using (Html.BeginForm("AddNewAlbum", "StoreManager", FormMethod.Post))
            {
                <input type="hidden" name="AlbumId" value=@Model.AlbumId />

                <table>                 
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.SelectGenreId)</td>
                        <td>@Html.DropDownListFor(model => model.SelectGenreId, Model.SelectGenre, "Select Genre")</td>
                    </tr>

                    <tr>
                        <td>@Html.DisplayNameFor(model => model.SelectArtistId)</td>
                        <td>@Html.DropDownListFor(model => model.SelectArtistId, Model.SelectArtist, "Select Artist")</td>
                    </tr>

                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Title)</td>
                        <td>
                            <input type="text" name="Title" value=@Model.Title />
                        </td>
                    </tr>

                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Price)</td>
                        <td>
                            <input type="text" name="Price" value=@Model.Price />
                        </td>
                    </tr>

                    <tr>
                        <td>@Html.DisplayNameFor(model => model.AlbumArtUrl)</td>
                        <td>
                            <input type="text" name="AlbumArtUrl" value=@Model.AlbumArtUrl />
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <input type="submit" value="Add New Album">
                        </td>
                        <td>
                            <a href="@Url.Action("Index", "StoreManager")">
                                Cancel
                            </a>  
                        </td>
                    </tr>
                </table>
            }
        </div>
        <br />

        <p>
            There is at least one box that is empty or if in price the value submitted was not at least 0.01. 
            Please correct your errors
        </p>
    }
}

MvcMusicStore/Views/StoreManager/Delete.cshtml
@model MvcMusicStore.Models.Album

<p1>Delete Album</p1>
<br />
<br />

<table>
    <tr>
        <td>Genre</td>
        <td>@Model.GenreName</td>
    </tr>

    <tr>
        <td>Artist</td>
        <td>@Model.ArtistName</td>
    </tr>

    <tr>
        <td>Title</td>
        <td>@Model.Title</td>
    </tr>

    <tr>
        <td>Price</td>
        <td>@Model.Price</td>
    </tr>

    <tr>
        <td>AlbumArtUrl</td>
        <td>@Model.AlbumArtUrl</td>
    </tr>

    <tr>
        <td>
            <a href="@Url.Action("DeleteConfirmation", "StoreManager", new { AlbumId = @Model.AlbumId })"> 
                Delete 
            </a>
        </td>

        <td>
            <a href="@Url.Action("Index", "StoreManager")"> 
                Back to List 
            </a>
        </td>
    </tr>
</table>

MvcMusicStore/Views/StoreManager/DeleteAlbum.cshtml
<p> Album successfully deleted </p>

<a href="@Url.Action("Index", "StoreManager")"> 
    Back to List
</a>

MvcMusicStore/Views/StoreManager/DeleteConfirmation.cshtml
@model MvcMusicStore.Models.Album

<h3>
    <i>Delete Confirmation</i>
</h3>
<br />

<p>Are you sure you want to delete the album titled <b>@Model.Title</b>?</p>

<a href="@Url.Action("DeleteAlbum", "StoreManager", new { AlbumId = @Model.AlbumId })"> 
    Delete 
</a>

<br />

<a href="@Url.Action("Index", "StoreManager")"> 
    Back to List 
</a>

MvcMusicStore/Views/StoreManager/Details.cshtml
@model MvcMusicStore.Models.Album

<p1> Album Details</p1>
<br /> 
<br />

<table>
    <tr> 
        <td>Genre</td>
        <td>@Model.GenreName</td>
    </tr>

    <tr>
        <td>Artist</td>
        <td>@Model.ArtistName</td>
    </tr>

    <tr>
        <td>Title</td>
        <td>@Model.Title</td>
    </tr>

    <tr>
        <td>Price</td>
        <td>@Model.Price</td>
    </tr>

    <tr>
        <td>AlbumArtUrl</td>
        <td>@Model.AlbumArtUrl</td>
    </tr>

    <tr>
        <td>
            <a href="@Url.Action("Edit", "StoreManager", 
                new { AlbumId = @Model.AlbumId, GenreId = @Model.GenreId,   ArtistId = @Model.ArtistId })"
            > 
                Edit
            </a>
        </td>

        <td>
            <a href="@Url.Action("Index", "StoreManager")"> 
                Back to List
            </a>
        </td>
    </tr>
</table>

MvcMusicStore/Views/StoreManager/Edit.cshtml
@model MvcMusicStore.Models.Album

@{
    ViewData["Title"] = "Edit Album";
    bool isPost = Convert.ToBoolean(ViewData["isPost"]);
    bool indicator = Convert.ToBoolean(ViewData["indicator"]);
}

<div>
    @if (isPost == false)
    {
        @using (Html.BeginForm("Edit", "StoreManager", FormMethod.Post))
        {
            <input type="hidden" name="AlbumId" value=@Model.AlbumId />

            <table>
                <tr>
                    <td>@Html.DisplayNameFor(model => model.Genre)</td>
                    <td>
                        @Html.DropDownListFor(model => model.SelectGenreId, Model.SelectGenre)
                    </td>
                </tr>

                <tr>
                    <td>@Html.DisplayNameFor(model => model.ArtistName)</td>
                    <td>
                       @Html.DropDownListFor(model => model.SelectArtistId, Model.SelectArtist)
                    </td>
                </tr>

                <tr>
                    <td>@Html.DisplayNameFor(model => model.Title)</td>
                    <td>
                        @Html.EditorFor(model => model.Title)
                    </td>
                </tr>

                <tr>
                    <td>@Html.DisplayNameFor(model => model.Price)</td>
                    <td>
                        @Html.EditorFor(model => model.Price)
                    </td>
                </tr>

                <tr>
                    <td>@Html.DisplayNameFor(model => model.AlbumArtUrl)</td>
                    <td>
                        @Html.EditorFor(model => model.AlbumArtUrl)
                    </td>                  
                </tr>

                <tr>
                    <td><input type="submit" value="Save"></td>
                </tr>

                <tr>
                    <td> 
                        <a href="@Url.Action("Index", "StoreManager")"> 
                            Back to List
                        </a>
                    </td>
                </tr>
            </table>
        }
    }
    else
    {
        @if(indicator)
        {
            <p>Updated the album with ID: @Model.AlbumId</p>

            <a href="@Url.Action("Index", "StoreManager")"> 
                Click on the link to go back to the list of albums
            </a>
        }
        else
        {
            <div>
                @using (Html.BeginForm("Edit", "StoreManager", FormMethod.Post))
                {
                    <input type="hidden" name="AlbumId" value=@Model.AlbumId />

                    <table>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.SelectGenreId)</td>
                            <td>@Html.DropDownListFor(model => model.SelectGenreId, Model.SelectGenre, "Select Genre")</td>
                        </tr>

                        <tr>
                            <td>@Html.DisplayNameFor(model => model.SelectArtistId)</td>
                            <td>@Html.DropDownListFor(model => model.SelectArtistId, Model.SelectArtist, "Select Artist")</td>
                        </tr>

                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Title)</td>
                            <td>
                                <input type="text" name="Title" value=@Model.Title />
                            </td>
                        </tr>

                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Price)</td>
                            <td>
                                <input type="text" name="Price" value=@Model.Price />
                            </td>
                        </tr>

                        <tr>
                            <td>@Html.DisplayNameFor(model => model.AlbumArtUrl)</td>
                            <td>
                                <input type="text" name="AlbumArtUrl" value=@Model.AlbumArtUrl />
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <input type="submit" value="Add New Album">
                            </td>
                            <td>
                                <a href="@Url.Action("Index", "StoreManager")">
                                    Cancel
                                </a>  
                            </td>
                        </tr>
                    </table>
                }
            </div>
            <br />

            <p>
                There is at least one box that is empty or if in price the value submitted was not at least 0.01. 
                Please correct your errors
            </p>
        }
    }
</div>

MvcMusicStore/Views/StoreManager/Index.cshtml
@model MvcMusicStore.Models.AlbumList

@{
    ViewData["Title"]  = "List of Albums";
}

<table>
    <tr>
        <th>
            Genre
        </th>
        <th>
            Artist
        </th>
        <th>
            Title
        </th>
        <th>
            Price
        </th>
        <th>
            AlbumArtUrl
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.albumlist) 
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GenreName)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.ArtistName)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.AlbumArtUrl)
        </td>

        <td>
            <a href="@Url.Action("Edit", "StoreManager", new { AlbumId = item.AlbumId, GenreId = item.GenreId, ArtistId = item.ArtistId })">
                Edit
            </a> |

            <a href="@Url.Action("Details", "StoreManager", new { AlbumId = item.AlbumId, GenreId = item.GenreId, ArtistId = item.ArtistId })">
                Details
            </a> |

            <a href="@Url.Action("Delete", "StoreManager", new { AlbumId = item.AlbumId, GenreId = item.GenreId, ArtistId = item.ArtistId })">
                Delete
            </a>
        </td>
    </tr>
}
</table>

<p>
    <a href="@Url.Action("AddNewAlbum", "StoreManager")"> 
        Add a New Album
    </a>
</p>